project:
  type: website
  output-dir: docs

website:
  title: "Incendios Folgoso"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    css: '00_files/style.css'
    theme: lux
    highlight-style: zenburn

editor: visual

