project:
  type: website
  output-dir: docs

website:
  title: "ejemplo-incendio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    toc-location: left
    toc-title: 'Contents'
    number-sections: true
    css: '00_files/style.css'
    theme: lux
    highlight-style: zenburn

editor: visual

